version: 1
disable_existing_loggers: true

formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  error:
    format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: error
    filename: error.log
    maxBytes: 5242880 # 5MB
    backupCount: 20
    encoding: utf8

  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: debug.log
    maxBytes: 5242880 # 5MB
    backupCount: 20
    encoding: utf8

root:
  level: NOTSET
  handlers: [console, error_file_handler, debug_file_handler]
  propagate: yes

loggers:
  <module>:
    level: INFO
    handlers: [console, error_file_handler, debug_file_handler]
    propagate: no

  <module.x>:
    level: DEBUG
    handlers: [error_file_handler, debug_file_handler]
    propagate: yes


